# dotfile manager: zgenom
.local/share/zgenom:
  type: git-repo
  url: https://github.com/jandamm/zgenom.git
  clone:
    args: [ "--depth", "1" ]

{{ if eq .chezmoi.os "linux" -}}
# shell prompt: starship
# can be brew installed on MacOs
.local/bin:
  type: archive
  url: "https://github.com/starship/starship/releases/download/{{ (gitHubLatestRelease "starship/starship").TagName }}/starship-x86_64-unknown-linux-gnu.tar.gz"
  refreshPeriod: "168h"

# script to remove old linux kernels so /boot doesn't fill up
.local/bin/kernel-clean:
  type: file
  url: "https://raw.githubusercontent.com/plepe/kernel-clean/master/kernel-clean"
  executable: true
  refreshPeriod: "744h"
{{ end -}}
