# https://mise.jdx.dev/configuration/settings.html

[settings]
not_found_auto_install = false

use_versions_host_track = false

lockfile = true
lockfile_platforms = ["linux-x64"]

python.uv_venv_auto = "source"
idiomatic_version_file_enable_tools = ["go", "node", "python"]

[settings.github]
credential_command = 'gh auth token --hostname "${MISE_CREDENTIAL_HOST}"'
use_git_credentials = true

[tools]
# languages
go = "latest"
node = "lts"
python = { version = "latest", postinstall = "~/.local/bin/mise sync python --uv" }

# package managers
pnpm = { version = "latest", postinstall = "pnpm completion zsh > ~/.config/zsh/completions/_pnpm" }
uv = { version = "latest", postinstall = "uv generate-shell-completion zsh > ~/.config/zsh/completions/_uv" }

# dev tools
atuin = { version = "latest", postinstall = "atuin gen-completions --shell zsh > ~/.config/zsh/completions/_atuin" }
bat = { version = "latest", postinstall = "bat --completion zsh > ~/.config/zsh/completions/_bat" }
dive = { version = "latest", postinstall = "dive completion zsh > ~/.config/zsh/completions/_dive" }
fd = "latest"
fzf = "latest"
jq = "latest"
mkcert = "latest"
ollama = "latest"
opencode = { version = "latest", postinstall = "opencode completion zsh > ~/.config/zsh/completions/_opencode" }
ripgrep = { version = "latest", postinstall = "rg --generate=complete-zsh > ~/.config/zsh/completions/_rg" }
shellcheck = "latest"
shfmt = "latest"
starship = { version = "latest", postinstall = "starship completions zsh > ~/.config/zsh/completions/_starship" }
task = { version = "latest", postinstall = "task --completion zsh > ~/.config/zsh/completions/_task" }
yq = { version = "latest", postinstall = "yq completion zsh > ~/.config/zsh/completions/_yq" }
zoxide = "latest"

# kubernetes
helm = { version = "latest", postinstall = "helm completion zsh > ~/.config/zsh/completions/_helm" }
helm-diff = { version = "latest", depends = ["helm"], postinstall = "helm plugin install $MISE_TOOL_INSTALL_PATH/diff" }  # required for helmfile
helmfile = { version = "latest", postinstall = "helmfile completion zsh > ~/.config/zsh/completions/_helmfile" }
kind = { version = "latest", postinstall = "kind completion zsh > ~/.config/zsh/completions/_kind" }
kubectl = { version = "latest", postinstall = "kubectl completion zsh > ~/.config/zsh/completions/_kubectl" }
