name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install zsh
        run: |
          sudo apt-get update
          sudo apt-get install zsh
      - name: chezmoi install
        run: |
          ./install.sh
          echo "install script finished"

          echo "\nhome directory"
          ls -a $HOME

          echo "\n.config directory"
          ls -a "$HOME/.config"
      - name:
        run: |
          echo "\n.profile"
          cat "$HOME/.profile" && source "$HOME/.profile"

          echo "\n.zshenv"
          cat "$HOME/.zshenv" && source "$HOME/.zshenv"

          echo "\n.zshrc"
          cat "$HOME/.config/zsh/.zshrc" && source "$HOME/.config/zsh/.zshrc"
        shell: zsh --errexit {0}
