name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo_task() {
            printf "\033[0;34m--> %s\033[0m\n" "$*"
          }

          ./install.sh
          echo "install script finished"

          echo_task home
          ls -a $HOME

          echo_task .config
          ls -a "$HOME/.config"

          echo_task .profile
          cat "$HOME/.profile" && source "$HOME/.profile"

          echo_task .zshenv
          cat "$HOME/.zshenv" && source "$HOME/.zshenv"

          echo_task .zshrc
          cat "$HOME/.config/zsh/.zshrc" && source "$HOME/.config/zsh/.zshrc"
        shell: zsh --errexit {0}
