name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          set -ex

          ./install.sh
          echo "::debug::install script finished"

          echo "::debug::home"
          ls -a $HOME

          echo "::debug::config"
          ls -a "$HOME/.config"

          echo "::debug::testing profile"
          source ~/.config/.profile

          echo "::debug::testing zshenv"
          source ~/.config/.zshenv

          echo "::debug::testing zshrc"
          source ~/.config/zsh/.zshrc

