name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install zsh and fzf
        run: |
          sudo apt-get update
          sudo apt-get install zsh fzf
      - name: chezmoi install
        run: |
          echo_task() {
            printf "\033[0;34m--> %s\033[0m\n" "$*"
          }

          ./install.sh

          echo_task 'home directory'
          ls -a $HOME

          echo_task 'config directory'
          ls -a "$HOME/.config"
      - name: test environment
        run: |
          echo_task() {
            printf "\033[0;34m--> %s\033[0m\n" "$*"
          }

          echo_task .profile
          cat "$HOME/.profile" && source "$HOME/.profile"

          echo_task .zshenv
          cat "$HOME/.zshenv" && source "$HOME/.zshenv"

          echo_task .zshrc
          cat "$HOME/.config/zsh/.zshrc" && source "$HOME/.config/zsh/.zshrc"
        shell: zsh {0}
        env:
          # This can't be done in a non-interactive shell
          ZGEN_AUTOLOAD_COMPINIT: 0
          # Disable oh-my-zsh warning about runner's completion environment
          ZSH_DISABLE_COMPFIX: "true"
